### ISSUE TITLE
Add a top-level config parameter to disable telemetry. 

### ISSUE THREAD

**Issue by JackHopkins** [monkeypatch/monkeypatch.py#89]
Currently, we automatically track usage of MP to help understand how people are using it.

There is currently no way to turn this off. Users may want to disable telemetry for privacy reasons.

We should add a top-level global config parameter for users to opt-out if necessary. The syntax could look something like this:

```python
Monkey.telemetry(disable=True)
```

**Comment by JackHopkins** [comment]
Actually, this should be added as a new *kwarg to the existing (newly added) `Monkey.configure` global method:

```
monkey.configure(disable_telemetry=True)
```

**Comment by cosmastech** [comment]
@JackHopkins where is the `configure` method defined? I don't see it within src/monkey.py
